"""fix

Revision ID: 25e9a5111bf7
Revises: 756f422e896e
Create Date: 2020-03-25 01:37:59.015638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e9a5111bf7'
down_revision = '756f422e896e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('course_identifier')
    op.drop_table('task')
    op.drop_table('o_auth1_token')
    op.drop_table('post')
    # ### end Alembic commands ###
