"""Move relationship attributes to the courseidentifier model

Revision ID: 5bb8ac9664ff
Revises: 3b1313f68c55
Create Date: 2020-11-03 17:24:17.852369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb8ac9664ff'
down_revision = '3b1313f68c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_identifier', schema=None) as batch_op:
        batch_op.drop_column('course_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_identifier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_color', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
