"""Store user ids from schoology

Revision ID: 5bdc5eeb6cdf
Revises: 7c1f73bb3770
Create Date: 2019-06-02 16:17:21.522783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdc5eeb6cdf'
down_revision = '7c1f73bb3770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_filter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('positive', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schoologyfilter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_identifier',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('course_name', sa.String(length=120), nullable=True),
    sa.Column('course_filter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_filter_id'], ['course_filter.id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_identifier')
    op.drop_table('schoologyfilter')
    op.drop_table('course_filter')
    # ### end Alembic commands ###
