"""Store user timezone

Revision ID: 5cac9461f0a3
Revises: 4f5863b5d741
Create Date: 2020-03-27 13:11:43.692991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cac9461f0a3'
down_revision = '4f5863b5d741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timezone', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone')
    # ### end Alembic commands ###
