"""Reset migrations

Revision ID: 91c25cef0ec6
Revises: 5bdc5eeb6cdf
Create Date: 2019-06-21 18:19:27.487302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c25cef0ec6'
down_revision = '5bdc5eeb6cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_identifier', sa.Column('course_color', sa.Integer(), nullable=True))
    op.add_column('course_identifier', sa.Column('user_colors_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_identifier', 'user', ['user_colors_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_identifier', type_='foreignkey')
    op.drop_column('course_identifier', 'user_colors_id')
    op.drop_column('course_identifier', 'course_color')
    # ### end Alembic commands ###
