"""Change field names

Revision ID: 997576219c86
Revises: 77e9a06b9468
Create Date: 2020-05-21 01:32:43.155347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997576219c86'
down_revision = '77e9a06b9468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.alter_column('course_identifier', 'course_id', new_column_name='id', existing_type=sa.String(36))
    op.alter_column('course_identifier', 'course_name', new_column_name='name', existing_type=sa.String(120))
    op.alter_column('course_identifier', 'course_realm', new_column_name='realm', existing_type=sa.String(120))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.alter_column('course_identifier', 'id', new_column_name='course_id', existing_type=sa.String(36))
    op.alter_column('course_identifier', 'name', new_column_name='course_name', existing_type=sa.String(120))
    op.alter_column('course_identifier', 'realm', new_column_name='course_realm', existing_type=sa.String(120))
    # ### end Alembic commands ###
