"""Add course color model

Revision ID: dd81b058eea1
Revises: 97384747c74a
Create Date: 2020-10-29 15:10:10.544928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd81b058eea1'
down_revision = '97384747c74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_color',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course_identifier.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_color')
    # ### end Alembic commands ###
